baseurl: "/fund-students" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://htc-ccis1505.github.io/" # the base hostname & protocol for your site
title: "CCIS 1505 Fund. of Programming"

exclude:
  - "README.md"
  - "Gemfile"
